#!/bin/sh

BOOTSTRAPD_DIR="${HOME}/.config/yadm/bootstrap.d"

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com/faku99/dotfiles.git"

echo "Updating apt repositories..."
sudo apt-get update

execute() {
    local SCRIPT="${BOOTSTRAPD_DIR}/$1"

    if [ -e "${SCRIPT}" ]; then
        clear
        echo "+++ Setting up $2 +++"
        sleep 1
        bash ${SCRIPT}
    fi
}

execute 00-apt "apt packages"

exit 0

echo "Installing oh-my-zsh"
sh -c "$(wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"

echo "Setting up i3"
mkdir -p ${HOME}/.local/bin
wget https://github.com/deadc0de6/i3smartfocus/blob/main/i3smartfocus/i3smartfocus.py -O ${HOME}/.local/bin/i3smartfocus.py

echo "Setting up oh-my-zsh"
rm ${HOME}/.zshrc
mv ${HOME}/.zshrc.pre-oh-my-zsh ${HOME}/.zshrc
source ${HOME}/.zshrc

exit 0
