import = [
    "~/.config/alacritty/themes/themes/dracula_plus.toml"
]

[cursor.style]
blinking = "Never"
shape = "Block"

[window]
opacity = 0.8

[font]
size = 11
normal = { family = "RobotoMono Nerd Font", style = "Regular" }
